### ISSUE TITLE
User Flow

### ISSUE THREAD

**Issue by sbryant40** [kseveur/SWEngineeringTeam10#17]
Research the page navigation on what the user will see

**Comment by alieu526** [comment]
![usernavigation flow](https://user-images.githubusercontent.com/21344862/45991731-3d1e9380-c054-11e8-9cfe-2c92e46afbda.jpg)

Concept diagram for the navigation of the application

**Comment by alieu526** [comment]
We will continue to modify what will need in the future as we add more features, but for now we have a starting idea to begin with.
