### ISSUE TITLE
Refine Search options

### ISSUE THREAD

**Issue by sbryant40** [kseveur/SWEngineeringTeam10#18]
Refine both regular and advance search options. Will need to talk with backend team to what exactly we can search for through LinkedIn

**Comment by ghost** [comment]
These are search fields that we will have access to without probing linked in for permissions
[https://developer.linkedin.com/docs/fields/basic-profile](url)
[https://developer.linkedin.com/docs/fields/location](url)
[https://developer.linkedin.com/docs/fields/positions](url)
Courtesy of our backend team
We have also run into a roadblock with our education search fields as they require permissions from LinkedIn. We will discuss this with our backend team on who wants to request the permissions from LinkedIn. Below are the search fields that require permissions.
[https://developer.linkedin.com/docs/fields/education](url)

**Comment by kla3** [comment]
I did not mean to close the issue as we will need updates on the education fields. Reopening it for updates.

**Comment by ghost** [comment]
I will be closing this issue and moving this topic to the "Research Linked In" Epic as it is a relevant subtopic and is already a part of the research that is being done there.
