### ISSUE TITLE
Research JavaFX

### ISSUE THREAD

**Issue by kseveur** [kseveur/SWEngineeringTeam10#4]
As a Software Developer
I want to better understand JavaFX
So that I can understand how to best use its capabilities for the LinkedIn Crawler application

**Comment by kseveur** [comment]
As a Software Developer
I want to better understand JavaFX
So that I can understand how to best use its capabilities for the LinkedIn Crawler application

**Comment by kseveur** [comment]
Kevin La, 
Why are we assigned to the same task? You should I assign yourself to a different task.

**Comment by ghost** [comment]
Cleared it up in class. I will assign myself to another task.
